---
# handlers file for prometheus-proxy
- name: 'restart prometheus'
  systemd:
    name: prometheus.service
    daemon_reload: true
    state: restarted

- name: 'reload firewall'
  systemd:
    name: firewall.service
    state: restarted
    daemon_reload: yes
