---
# defaults file for prometheus-proxy
targets: []
prometheus_archive_url: 'https://github.com/prometheus/prometheus/releases/download/v2.37.0/prometheus-2.37.0.linux-amd64.tar.gz'
prometheus_bin_dir: '/usr/local/bin'
prometheus_conf_dir: '/etc/prometheus'
prometheus_db_dir: '/var/lib/prometheus/'
target_port: 9100
prometheus_port: 9090
ip_query: "[*].ip_addresses[0].address"
# prometheus_listen_address is used to scrape the prometheus proxy. 
prometheus_listen_address: "{{ interfaces | json_query(ip_query) |ipaddr('10.0.0.0/8') | first | ipaddr('address') }}"



