---
# handlers file for wireguard
- name: restart wireguard
  service:
    name: "wg-quick@{{ wireguard_interface }}"
    state: "{{ item }}"
  loop:
    - stopped
    - started
  when:
    - wireguard__restart_interface
    - wireguard_service_enabled == "yes"
  listen: "reconfigure wireguard"

# sometimes even though synconf synchronises the configuration file, it is usually not sufficient. The wireguard interface
# has to be restarted.
- name: syncconf wireguard
  shell: |
    set -o errexit
    set -o pipefail
    set -o nounset
    systemctl is-active wg-quick@{{ wireguard_interface|quote }} || systemctl start wg-quick@{{ wireguard_interface|quote }}
    wg syncconf {{ wireguard_interface|quote }} <(wg-quick strip /etc/wireguard/{{ wireguard_interface|quote }}.conf)
    exit 0
  args:
    executable: "/bin/bash"
  when:
    - not wireguard__restart_interface
    - wireguard_service_enabled == "yes"
  listen: "reconfigure wireguard"
